force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Page__c/Form_Page__c.object-meta.xml
<CustomObject>
    <label>Form Page</label>
    <nameField>
        <displayFormat>FP-{000000}</displayFormat>
        <label>Form Page</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Page__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Pages</relationshipLabel>
    <relationshipName>Form_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Section__c/Form_Section__c.object-meta.xml
<CustomObject>
    <label>Form Section</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Form Section</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FormCreationHelper.cls
/**
 * @description       : help class for when a form is created ensuring the base template is configured correctly
 * @author            : daniel@hyphen8.com
 * @last modified on  : 05-11-2021
 * @last modified by  : daniel@hyphen8.com
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   10/05/2021   daniel@hyphen8.com   Initial Version
**/
public with sharing class FormCreationHelper {


    public static void afterInsertSetupBaseForm(string recordId){

        Form_Page__c fp = new Form_Page__c(Form__c = recordId, Title__c = 'First Page', Order__c = 1);
        insert fp;

        Form_Section__c fs = new Form_Section__c(Form_Page__c = fp.Id, Title__c = 'First Section', Order__c = 1);
        insert fs;
    
    }

}